### ISSUE TITLE
Data Sets shared on google drive are missing

### ISSUE THREAD

**Issue by scott-weeden** [microsoft/prose#65] opened 2023-06-19 09:43 UTC
The readme has a link to datasets that can't be accessed:

https://drive.google.com/drive/folders/1gBZuhV42VHhrwsiKpEA4dLYVdiiXbUGp?usp=sharing

![image](https://github.com/microsoft/prose/assets/63826817/a2e80e03-e39a-4b62-b2ee-75f9ee6d89b4)

**Comment by josepablocam** [comment] 2023-06-19 17:34
@scott-weeden  thanks for pointing this out! It looks like this link was created as part of a conference artifact evaluation process. We're reaching out to the original creator/author to get the underlying dataset and fix the link. Thanks!

**Comment by josepablocam** [comment] 2023-06-19 17:34
fyi @simmdan

**Comment by afariha** [comment] 2023-06-20 04:24
@scott-weeden please refer to this: https://github.com/afariha/ConformanceConstraintsReproducibility

**Comment by josepablocam** [comment] 2023-06-27 15:13
This was now patched as part of our regular public release. I am closing this issue as resolved.

**Closed** 2023-06-27 15:13 UTC
